spring:
  application:
    name: spring-boot-rds-crud

  jpa:
    properties:
      hibernate:
        # Note: You can remove dialect in Spring Boot 3+ / Hibernate 6+
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: 'true'
          batch_size: '50'
    hibernate:
      ddl-auto: 'update'

  datasource:
    driver-class-name: com.amazonaws.secretsmanager.sql.AWSSecretsManagerPostgreSQLDriver
    url: jdbc-secretsmanager:postgresql://myapp-rds-postgres.conyo2aki51n.us-east-1.rds.amazonaws.com:5432/springbootcrud
    username: ce-dev/rds/db-credentials

  main:
    lazy-initialization: 'true'

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    throw-exception-if-no-handler-found: 'true'

  resources:
    add-mappings: 'false'

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

cors:
  allowed:
    origins: '*'

application:
  description: 'CRUD Application on AWS'
  name: 'spring-boot-crud-app'

build:
  timestamp: '2026-09-16T13:48:00Z'
  version: '0.0.1-SNAPSHOT'

modules:
  logging:
    logs:
      folder:
        path: ./logs
    application:
      name: 'spring-boot-crud-app'

server:
  port: '8080'

logging:
  level:
    org:
      hibernate:
        type: TRACE
        SQL: DEBUG
